services:
  rozy-auth-be-1:
    build:
      context: ../..
      dockerfile: docker/source/Dockerfile
    env_file:
      - ../../.env
    environment:
      TZ: Asia/Saigon
    networks:
      - bridge
  rozy-auth-be-2:
    build:
      context: ../..
      dockerfile: docker/source/Dockerfile
    env_file:
      - ../../.env
    environment:
      TZ: Asia/Saigon
    networks:
      - bridge

networks:
  bridge:
    external: true
