services:
  rozy-auth-be-1:
    build:
      context: ../..
      dockerfile: docker/source/Dockerfile
    env_file:
      - ../../.env
    environment:
      TZ: Asia/Saigon
    ports:
      - "4200:4600"
    networks:
      - vault
  # rozy-auth-be-2:
  #   build:
  #     context: ../..
  #     dockerfile: docker/source/Dockerfile
  #   env_file:
  #     - ../../.env
  #   environment:
  #     TZ: Asia/Saigon
  #   networks:
  #     - vault

networks:
  vault:
    driver: bridge
