services:
  rozy-auth-be-1:
    build:
      context: ../..
      dockerfile: docker/source/Dockerfile
    env_file:
      - ../../.env
    environment:
      TZ: Asia/Saigon
    networks:
      - vault

networks:
  vault:
    driver: bridge
