services:
  rozy-auth-be-1:
    build:
      context: ../..
      dockerfile: docker/source/Dockerfile
    env_file:
      - ../../.env
    environment:
      TZ: Asia/Saigon
    networks:
      - local
  rozy-auth-be-2:
    build:
      context: ../..
      dockerfile: docker/source/Dockerfile
    env_file:
      - ../../.env
    environment:
      TZ: Asia/Saigon
    networks:
      - local

networks:
  local:
    external: true
